### ISSUE TITLE
Radius parameter not working?

### ISSUE THREAD

**Issue by goob47** [chrisdhaan/CDYelpFusionKit#1]
Despite setting a radius of 1609 to find businesses within 1 mile of my location, I'm still receiving businesses that are outside of that radius.

**Comment by chrisdhaan** [comment]
@goob47 the `radius` parameter is being passed to the Yelp Fusion API successfully. It is my experience that this parameter is not a hard filter, meaning you may still receive results outside of the radius. I would check out the Yelp Fusion documentation or reach out to the Yelp Developers Portal directly if you need more information around how the parameter works within the API.

**Comment by goob47** [comment]
That's what I figured. Thanks! :)
