### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by bureauvk** [chrisdhaan/CDYelpFusionKit#15]
Hi Chris, amazing wrapper. I like it. Thanks for your work.

Are you planning on updating so this Pod will support Swift 5? The AlamofireObjectMapper dependency has to be updated to 6.0.0 I believe.

**Comment by chrisdhaan** [comment]
@bureauvk yes I do plan on making this update some time in the next three weeks. Apologies for not having it out sooner but I have a lot going on right now and can't get to it sooner.

**Comment by filsv** [comment]
Hi @chrisdhaan , Swift 5 version already updated? :)

**Comment by chrisdhaan** [comment]
@bureauvk @filsv addressed in #19
