### ISSUE TITLE
CDYelpFusionKit dependencies do not work with Alamofire 5+, Alamofireimage 4.1, Alamofire 6.2.0

### ISSUE THREAD

**Issue by KevinVladG** [chrisdhaan/CDYelpFusionKit#18]
Will there be an update to using updated Alamofire repos

## What did you do?
install Yelp fusion kit

## What did you expect to happen?
be able to use Alamofireimage to get url images from the yelp api to show easier

## What happened instead?
Error when installing pod

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    AlamofireImage (~> 4.1) was resolved to 4.1.0, which depends on
      Alamofire (~> 5.1)

    CDYelpFusionKit (= 1.5.1) was resolved to 1.5.1, which depends on
      AlamofireObjectMapper (= 5.2.0) was resolved to 5.2.0, which depends on
        Alamofire (~> 4.7)

**CDYelpFusionKit version: 1.5.1
**Xcode version: Version 11.5 (11E608c)
**Swift version: Swift 5
**Platform(s) running CDYelpFusionKit: IOS 13.5
**macOS version running Xcode: 10.15.6 Beta (19G46c)

**Comment by chrisdhaan** [comment]
@KevinVladG addressed in #19
