### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by xixinjie** [chrisdhaan/CDYelpFusionKit#2]
Hi Christopher,
Thank you for wrapping Yelp Fusion API. With your lib, I don't need to write codes from scratch to use the API.

Yet I got an exception **fatal error: unexpectedly found nil while unwrapping an Optional value** when I tried to use it in my project. Then I tried to run the iOS example you provided, but nothing was printed as expected in console.

Could you please fix the issue?

**Comment by xixinjie** [comment]
iOS example is working, forgot to update clientId and clientSecret.

**Comment by chrisdhaan** [comment]
@xixinjie glad you were able to get the iOS example running. Can I close this issue or did you still need assistance?

**Comment by xixinjie** [comment]
@chrisdhaan  It is working perfectly with your lib in my project. Thank you! 
```swift
// Setup CDYelpAPIClient instance with my own clientId and clientSecret
CDYelpFusionKitManager.shared.configure()
```

BTW, regarding installation, I preferred Carthage but failed with underlying dependencies (ObjectMapper) problem. Finally I switched to submodule way and it's working now.
