### ISSUE TITLE
SearchBusinesses returns NIL for hours

### ISSUE THREAD

**Issue by JakeEllis** [chrisdhaan/CDYelpFusionKit#21]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

 CDYelpFusionKitManager.shared.apiClient.cancelAllPendingAPIRequests()
        // Query Yelp Fusion API for business results
        CDYelpFusionKitManager.shared.apiClient.searchBusinesses(byTerm: currentActivity,
                                                                 location: nil,
                                                                 latitude: lat,
                                                                 longitude: long,
                                                                 radius: searchRadiusMeters,
                                                                 categories: nil,
                                                                 locale: .english_unitedStates,
                                                                 limit: 50,
                                                                 offset: 0,
                                                                 sortBy: .bestMatch,
                                                                 priceTiers: budgetPriceTier,
                                                                 openNow: nil,
                                                                 openAt: selecteDateInt,
                                                                 attributes: nil)

## What did you expect to happen?

I expect to see the open and close time of the returned businesses

## What happened instead?

The Hours data is always nil for all businesses.

## CDYelpFusionKit Environment

**CDYelpFusionKit version:**  
**Xcode 11.3.1**  
**Swift 5**  
**Platform(s) running CDYelpFusionKit: iPhone **  
**macOS version running Xcode: 10.15.3**

## Demo Project

![Screen Shot 2020-09-02 at 12 11 13 PM](https://user-images.githubusercontent.com/3925187/92009114-052b2b00-ed16-11ea-9696-75dd8dea010e.png)

**Comment by chrisdhaan** [comment]
@JakeEllis apologies for the delayed response. I will look into this

**Comment by chrisdhaan** [comment]
@JakeEllis not all businesses populate the hours property. I've loaded up the example and the response returned from the `business/id` endpoint returns a business with hours populated if you need an example that has them

**Comment by chrisdhaan** [comment]
`hours` is now only returned with the object in the supported endpoint. Closing do to lack of activity.
