### ISSUE TITLE
Swift package manager fails on new project.

### ISSUE THREAD

**Issue by KevinVladG** [chrisdhaan/CDYelpFusionKit#26]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

## What did you do?

added dependency using GitHub link: https://github.com/chrisdhaan/CDYelpFusionKit.git

## What did you expect to happen?

Swift package manager add package dependencies.

## What happened instead?

Swift package resolution Failed with this error: 
Showing All Messages
invalidManifestFormat("/var/folders/nz/k_j22d4n10gbdpz67hfvwyw80000gn/T/TemporaryFile.6hCVyM.swift:45:17: error: missing argument label \'from:\' in call\n        .package(url: \"https://github.com/Alamofire/Alamofire.git\", \"5.2.2\")\n                ^\n                                                                    from: \n/var/folders/nz/k_j22d4n10gbdpz67hfvwyw80000gn/T/TemporaryFile.6hCVyM.swift:45:10: error: static member \'package\' cannot be used on instance of type \'Package.Dependency\'\n        .package(url: \"https://github.com/Alamofire/Alamofire.git\", \"5.2.2\")\n        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n        Package.Dependency\n/var/folders/nz/k_j22d4n10gbdpz67hfvwyw80000gn/T/TemporaryFile.6hCVyM.swift:46:17: error: missing argument label \'from:\' in call\n        .package(url: \"https://github.com/tristanhimmelman/ObjectMapper\", \"4.2.0\")\n                ^\n                                                                          from:", diagnosticFile: Optional(<AbsolutePath:"/Users/main/Library/Developer/Xcode/DerivedData/NEWAPP-apvpbgsnsxipjqbzshvhrvsdlotz/SourcePackages/ManifestLoading/cdyelpfusionkit.dia">)) in https://github.com/chrisdhaan/CDYelpFusionKit.git

## CDYelpFusionKit Environment

**CDYelpFusionKit version: 2.1.1
**Xcode version: Version 12.5.1 (12E507)
**Swift version: 5.0
**Platform(s) running CDYelpFusionKit: IOS
**macOS version running Xcode: Version 11.51 (20G80)

## Demo Project

New project "Hello World!" only showing at the moment.

**Comment by KevinVladG** [comment]
This is a SwiftUI project but Its just adding the package that fails

**Comment by KevinVladG** [comment]
Creating a PR for this Fix I believe it's a very simple change to the Package.swift file, that is needed.

**Comment by KevinVladG** [comment]
![Screen Shot 2021-08-09 at 4 54 08 AM](https://user-images.githubusercontent.com/47987527/128681628-c618c1b6-40d9-4816-88c2-cdb975d518e1.png)


I was able to add the dependency when changing the following code:

![Screen Shot 2021-08-09 at 4 55 00 AM](https://user-images.githubusercontent.com/47987527/128681836-b195ea7c-dfdf-4492-955b-43aee10dc894.png)

However, when building I get these errors:

![Screen Shot 2021-08-09 at 4 56 27 AM](https://user-images.githubusercontent.com/47987527/128681921-51ef886e-435e-4050-8735-167a1b073aaf.png)


anyone got any ideas?

**Comment by KevinVladG** [comment]
Cleaned the build folder and now I'm only left with one error:

![Screen Shot 2021-08-09 at 5 20 20 AM](https://user-images.githubusercontent.com/47987527/128684823-64265938-50e9-4fcc-8741-7f0b651bab3b.png)

progress!

**Comment by Mcrich23** [comment]
Can you please walk me through how you did this? I am have the exact same issue

**Comment by KevinVladG** [comment]
@Mcrich23 check out my pull request, you might have to fork my branch, hopefully @chrisdhaan can merge this change for those who want to use swift package manager

**Comment by Mcrich23** [comment]
How do I install it?

**Comment by Mcrich23** [comment]
> Creating a PR for this Fix I believe it's a very simple change to the Package.swift file, that is needed.

What is the change? Can I get this file and can you tell me what to replace where?

**Comment by KevinVladG** [comment]
you install it like any other swift package.... I don't know what you mean my guy check the PR??? it shows you the file changes. there's no file

**Comment by chrisdhaan** [comment]
@KevinVladG @Mcrich23 I've released `3.0.0` today which includes the fix. Let me know if you run into any other issues.

**Comment by KevinVladG** [comment]
@chrisdhaan version 3.0.0 fails for: 

![Screen Shot 2021-09-14 at 11 56 05 PM](https://user-images.githubusercontent.com/47987527/133368219-f4e46fbe-012c-413a-b6bd-37fb5dd0a9cd.png)


it's a simple change in the Package.swift file, in your targets, the name should come before for the dependencies. 

![Screen Shot 2021-09-14 at 11 54 37 PM](https://user-images.githubusercontent.com/47987527/133368299-e096b825-b365-444a-94ea-bb89ceeb4601.png)


please let me know when this is fixed! will love to use the release version as soon as possible thank you for all the hardworking you have put into it also! I'm really happy with the changes you've made from you recent PR. Thank you!

**Comment by chrisdhaan** [comment]
@KevinVladG i'm pushing out a fix today and have added a CI test to avoid my breaking the config in the future

**Comment by chrisdhaan** [comment]
@KevinVladG I've released `3.0.1` which should work fine. If you could confirm for me that it's working on your end I'll close out this issue after.

**Comment by KevinVladG** [comment]
![Screen Shot 2021-09-18 at 12 55 17 AM](https://user-images.githubusercontent.com/47987527/133873065-f2adffde-b78c-4abf-b1d3-7fe37b74929a.png)
Success!!! no errors when adding swift package! green light to close this issue! Thank you @chrisdhaan for your hard work and timely response!!!
