### ISSUE TITLE
Fetching Categories

### ISSUE THREAD

**Issue by Mcrich23** [chrisdhaan/CDYelpFusionKit#30]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

## What did you do?

I tried to fetch a category title

## What did you expect to happen?

it to return a category title

## What happened instead?

`fetchCategories(forLocale) alias:  Response status code was unacceptable: 403.` was printed

## CDYelpFusionKit Environment

**CDYelpFusionKit version:**  3.0.0
**Xcode version:**  13
**Swift version:**  5.4
**Platform(s) running CDYelpFusionKit:**  iOS, iPadOS
**macOS version running Xcode:** 12

## Project

[https://www.icloud.com/iclouddrive/0jXKHd1Emfy9sBArWSaDvuzMw#Pickt](https://www.icloud.com/iclouddrive/0jXKHd1Emfy9sBArWSaDvuzMw#Pickt)

**Comment by chrisdhaan** [comment]
I'll take a look into this @Mcrich23

**Comment by Mcrich23** [comment]
Thx!

**Comment by chrisdhaan** [comment]
@Mcrich23 I tested the endpoint this morning and it seemed to be working. Are you still experiencing this issue?

**Comment by Mcrich23** [comment]
It works!
