### ISSUE TITLE
Hours always coming back nil

### ISSUE THREAD

**Issue by Mcrich23** [chrisdhaan/CDYelpFusionKit#35]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to get hours of yelp restaurants.

## What did you expect to happen?

Came back with hours

## What happened instead?

Came back nil

## CDYelpFusionKit Environment

**CDYelpFusionKit version: 3.1.0**  
**Xcode version: 13.4**  
**Swift version: 5.6**  
**Platform(s) running CDYelpFusionKit: ios**  
**macOS version running Xcode: 12.4**

**Comment by Mcrich23** [comment]
It doesn't even work in the example project

**Comment by chrisdhaan** [comment]
@Mcrich23 which endpoint are you querying?

**Comment by Mcrich23** [comment]
@chrisdhaan I am doing the business endpoint

**Comment by Mcrich23** [comment]
Update @chrisdhaan , it works, but I am trying to just do 20 in a row and it rate limits, is there anyway for the data to come back with the search?

**Comment by chrisdhaan** [comment]
@Mcrich23 I do not own the YelpFusion API. I only developed the interface to interact with it. You would have to request that functionality directly with yelp to have hours returned in the search API. As far as I can tell from the documentation only the business id endpoint supports hours returning.

**Comment by Mcrich23** [comment]
Ok. Thank you. SincerelyMorris RichmanHttps://mcrich23.comOn Dec 4, 2022, at 1:10 AM, Christopher de Haan ***@***.***> wrote:﻿
@Mcrich23 I do not own the YelpFusion API. I only developed the interface to interact with it. You would have to request that functionality directly with yelp to have hours returned in the search API. As far as I can tell from the documentation only the business id endpoint supports hours returning.

**Comment by chrisdhaan** [comment]
No problem @Mcrich23 . I'm going to close the issue.
