### ISSUE TITLE
Support Swift 4 by upgrading AlamofireObjectMapper to 5.0

### ISSUE THREAD

**Issue by xixinjie** [chrisdhaan/CDYelpFusionKit#4]
## What did you do?
Tried to install this lib via CocoaPods as per the guides, and use it in my app.

## What did you expect to happen?
Able to install and use

## What happened instead?
Able to install but failed to use it, with error: **toIntMax unavailable**
Please find related issue in [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper/issues?utf8=%E2%9C%93&q=toIntMax)

It should work in swift 4 via upgrading AlamofireObjectMapper to [5.0](https://github.com/tristanhimmelman/AlamofireObjectMapper/releases/tag/5.0.0) which support Swift 4.0

## CDYelpFusionKit Environment

**CDYelpFusionKit version:**  1.1.0
**Xcode version:**  9.0
**Swift version:**  Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
**Platform(s) running CDYelpFusionKit:**  MacOS
**macOS version running Xcode:** 10.12.6

## Demo Project
None

Oh man, it's better to have freestyle issue.

**Comment by chrisdhaan** [comment]
Hey @xixinjie . I'm working on updating to Swift 4 this week. I'm hoping to have `2.0.0` out by the end of the weekend.

**Comment by xixinjie** [comment]
Thank you @chrisdhaan . When it's done, I will change from submodule to Cocoapods to install the lib.

**Comment by chrisdhaan** [comment]
@xixinjie 

Here's an update from this weekend. I just finished up `1.2.0` which I'll be releasing tonight. `1.2.0` contains the rest of the frameworks core functionality. Over the next two days I'll be releasing `1.3.0` which contains macOS, watchOS, and tvOS support. I want to get all of this in for full backwards compatibility for Swift 3 users. Hopefully if this all goes well I'll be pushing `2.0.0` on Wednesday which will be Swift 4 ready.

**Comment by chrisdhaan** [comment]
@xixinjie I have started updating to Swift 4.0. Hoping to have `2.0.0` out within the next 24 hours.

**Comment by xixinjie** [comment]
@chrisdhaan Thank you man.

**Comment by xixinjie** [comment]
Ah, glad that you commited the changes for Swift 4.0. Looking forward to having it (1.4.0) released.

**Comment by chrisdhaan** [comment]
@xixinjie just finishing up some last documentation today and releasing `1.4.0` tonight.

**Comment by xixinjie** [comment]
@chrisdhaan Looks like not released yet due to build failure

**Comment by chrisdhaan** [comment]
@xixinjie `1.4.0` has been released. Please try installing and let me know how it works.

**Comment by xixinjie** [comment]
@chrisdhaan 👍 👍 👍   It works perfectly in Swift 4.0 now. Thank you so much. 

BTW, minor changes from 1.3.0 to 1.4.0: 
* `CDYelpCategoryFilter` changed to `CDYelpBusinessCategoryFilter`
* Block parameters in `searchBusiness` changed from `(response, error)` to `(response)`

**Comment by chrisdhaan** [comment]
@xixinjie thanks for pointing out those changes. I'll update the CHANGELOG.md. Afterwards to I have your permission to close out this issue?

**Comment by xixinjie** [comment]
@chrisdhaan Sure, please close it then.
