### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by davecom** [chrisdhaan/CDYelpFusionKit#5]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

Quickly scanning the source code it looks like there is not a lot that is iOS specific, other than the UIImage extensions. macOS support would be fantastic.

**Comment by chrisdhaan** [comment]
@davecom I completely agree. I'm finishing up a last bit of functionality and then updating the framework to Swift 4. Afterwards I plan on adding macOS, watchOS, and tvOS support. Hopefully can have it done in the next two weeks.

**Comment by davecom** [comment]
Thanks, that's awesome. Also thanks for making this library. It was sorely needed.

**Comment by chrisdhaan** [comment]
@davecom 

Here's an update from this weekend. I just finished up `1.2.0` which I'll be releasing tonight. `1.2.0` contains the rest of the frameworks core functionality. Over the next two days I'll be releasing `1.3.0` which contains macOS, watchOS, and tvOS support. I realized I wanted to get the OS update in before Swift 4 so Swift 3 users of the framework would have full framework functionality. Hopefully if this all goes well I'll have `1.3.0` out by Tuesday/Wednesday night.

**Comment by davecom** [comment]
Thanks for update. I'm going to be incorporating the framework in a macOS app, but I will likely not have time to work on it for a few weeks. I'll let you know if any issues come up when I do that. Thank you again.

**Comment by chrisdhaan** [comment]
@davecom `1.3.0` has been released with macOS, tvOS, and watchOS support.

**Comment by davecom** [comment]
@chrisdhaan I just wanted to let you know it's been working pretty well for me on macOS. Thank you! I am using Cocoa Bindings so I do have to add @objc and @objcMembers to most model classes as well as extending NSObject, but I imagine using the Objective-C runtime is not something most users of your library care about! Just those using Cocoa Bindings.

**Comment by chrisdhaan** [comment]
@davecom glad to hear things are going well. I generally don't develop for macOS so please don't hesitate to reach out if you run into issues.
