### ISSUE TITLE
Support Yelp API Key Authentication

### ISSUE THREAD

**Issue by davecom** [chrisdhaan/CDYelpFusionKit#7]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

Yelp announced today that they are deprecating token based access. I could be wrong but I think CDYelpFusionKit uses the token method.

They put the details at the bottom of the authentication page:
https://www.yelp.com/developers/documentation/v3/authentication

**Comment by chrisdhaan** [comment]
Thanks for opening this @davecom. I saw the announcement. I will hopefully have time to update the authentication process this weekend.

**Comment by chrisdhaan** [comment]
Holidays got a little busy. I'll work on implementing this over the next few days.

**Comment by chrisdhaan** [comment]
@davecom just cleaning up the documentation and will push this update today.

**Comment by davecom** [comment]
@chrisdhaan Thank you, Chris.

**Comment by chrisdhaan** [comment]
`1.5.0` has been released containing this update.

**Comment by davecom** [comment]
Thanks Chris!
