### ISSUE TITLE
Update CDYelpTransactionType

### ISSUE THREAD

**Issue by horea4** [chrisdhaan/CDYelpFusionKit#9]
As per your comment in CDYelpEnums, "Currently, only food delivery is supported and it is only supported in the U.S."

Please note, however, that according to Yelp:
"Current supported values are pickup, delivery and restaurant_reservation."

Just letting you know that you should update this when you get the chance.

**Comment by chrisdhaan** [comment]
Thanks for the info @horea4. I'll update this within the next few days.

**Comment by chrisdhaan** [comment]
@horea4 I have pushed an update that includes the new transaction types to master. If you pull from master you can get these changes. I will be releasing a new update in a few days that will also include those changes and will close this issue then.

**Comment by chrisdhaan** [comment]
Addressed in version `1.5.1`
